-- Create Schema for AI Processing Logs
create table if not exists processing_requests (
  id uuid primary key,
  filename text not null,
  status text not null, -- 'pending', 'processing', 'completed', 'failed', 'rejected'
  xero_invoice_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists processing_logs (
  id bigint generated by default as identity primary key,
  request_id uuid references processing_requests(id) on delete cascade,
  agent_name text not null,
  action text not null,
  status text not null, -- 'started', 'in-progress', 'completed', 'failed'
  details jsonb,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for performance
create index if not exists idx_processing_requests_xero_id on processing_requests(xero_invoice_id);
create index if not exists idx_processing_logs_request_id on processing_logs(request_id);

-- Optional: RLS Policies (if enabling Row Level Security)
-- alter table processing_requests enable row level security;
-- alter table processing_logs enable row level security;
